name: dockerpostgis

services:
  db:
    image: postgis/postgis
    restart: always
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meshtastic # default database
    volumes:
      - pg_data:/var/lib/postgresql/data
  pgadmin4:
    image: dpage/pgadmin4:8
    restart: always
    ports:
      - "1209:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@esmosolutions.es
      PGADMIN_DEFAULT_PASSWORD: esmosolutions
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pg_data:
  pgadmin_data: